PREFIX inf: <https://inference.es/app/onto#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX exa: <http://example.com/ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX fio: <http://purl.obolibrary.org/obo/fio#>

INSERT {
  ?s rdf:type exa:TestClass .
}

WHERE {
  ?s rdf:type fio:Candidate .
  ?s <http://purl.obolibrary.org/obo/RO_0000091> 'http://purl.obolibrary.org/obo/fio#PreventionFocus' .
  ?s exa:uses_intervention_property "PreventionFraming".
  ?s exa:performer_cardinality ?perf_cardinality
  FILTER ( ?perf_cardinality > "1"^^xsd:integer )
}
